sonar.verbose=true
sonar.login=dharam84-kkeeyy
sonar.projectKey=dharam84-kkeeyy_dharam
sonar.projectName=dharam
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jaco.xml
